/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Designed By Jonathan (https://sketchfab.com/designedbyjonathan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/neon-open-sign-a04c11ddadb4419392c94dc97e78e847
title: Neon Open Sign
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/neon.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 600]} scale={0.00001}>
        <group scale={500}>
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/neon.gltf');
